"""empty message

Revision ID: b47d4efbfd1b
Revises: 62cc3eb6a2ff
Create Date: 2025-03-13 16:57:05.786323

"""
from alembic import op
import sqlalchemy as sa


from alembic import op
import sqlalchemy as sa
import os

# revision identifiers, used by Alembic.
revision = 'b47d4efbfd1b'
down_revision = '62cc3eb6a2ff'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=False, server_default='user'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
